const CHANNELS=['etsy','tiktok','instagram','pinterest'];let products=[];let activeProductId=null;let activeChannel='etsy';const $=s=>document.querySelector(s);const log=(m,d)=>{$('#log').textContent=`[${new Date().toLocaleTimeString()}] ${m}${d?'\n'+JSON.stringify(d,null,2):''}\n\n`+$('#log').textContent};
async function init(){try{const r=await fetch('/api/health');const d=await r.json();$('#apiStatus').textContent=d.ok?'API ready':'API setup needed';$('#apiStatus').className=d.ok?'ready':'pending';renderConnectors(d.connectors||{})}catch{$('#apiStatus').textContent='Static preview mode';renderConnectors({})}const saved=localStorage.getItem('catalogflow-products');if(saved){products=JSON.parse(saved);render()}}
function save(){localStorage.setItem('catalogflow-products',JSON.stringify(products));render()}function arr(v){if(Array.isArray(v))return v;return String(v||'').split(/[|,]/).map(x=>x.trim()).filter(Boolean)}function slug(s){return String(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function normalizeProduct(p,i){return{id:p.id||slug(p.name||`product-${i+1}`),name:p.name||p.title||`Product ${i+1}`,collection:p.collection||'Everyday Wear',price:Number(p.price||0),colors:arr(p.colors),sizes:arr(p.sizes),frontDesign:p.frontDesign||p.design||'',backDesign:p.backDesign||'',scripture:p.scripture||'',image:p.image||'',productUrl:p.productUrl||'https://novanity33.com',selected:true,listings:p.listings||{},publishStatus:p.publishStatus||{}}}
function placeholder(name){return`data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="112" height="112"><rect width="100%" height="100%" fill="#242831"/><text x="50%" y="50%" fill="#d4af37" font-size="12" text-anchor="middle" dominant-baseline="middle">${name.slice(0,14)}</text></svg>`)}`}
function render(){$('#stats').innerHTML=[['Products',products.length],['Selected',products.filter(p=>p.selected).length],['Generated',products.filter(p=>Object.keys(p.listings||{}).length).length],['Published',products.filter(p=>Object.values(p.publishStatus||{}).some(x=>x==='published')).length]].map(([a,b])=>`<div class="stat"><span>${a}</span><b>${b}</b></div>`).join('');$('#productRows').innerHTML=products.map(p=>`<tr><td><input type="checkbox" ${p.selected?'checked':''} onchange="toggleProduct('${p.id}',this.checked)"></td><td><div class="product"><img class="thumb" src="${p.image||placeholder(p.name)}"><div><b>${p.name}</b><br><small>${p.colors.join(', ')||'No colors'} • ${p.sizes.join(', ')||'No sizes'}</small></div></div></td><td><span class="badge">${p.collection}</span></td><td>$${p.price.toFixed(2)}</td><td class="${Object.keys(p.listings).length?'ready':'pending'}">${Object.keys(p.listings).length?'Generated':'Not generated'}</td><td><div class="channels">${CHANNELS.map(c=>`<span>${c}: ${p.publishStatus[c]||'—'}</span>`).join('')}</div></td><td><button class="btn secondary" onclick="openEditor('${p.id}')">Review</button></td></tr>`).join('')}
window.toggleProduct=(id,v)=>{products.find(p=>p.id===id).selected=v;save()};$('#selectAll').onchange=e=>{products.forEach(p=>p.selected=e.target.checked);save()};$('#sampleBtn').onclick=async()=>{products=(await(await fetch('data/sample-products.json')).json()).map(normalizeProduct);save();log('Loaded sample catalog')};$('#clearBtn').onclick=()=>{products=[];save();log('Cleared catalog')};
$('#fileInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;const text=await f.text();const raw=f.name.endsWith('.csv')?parseCsv(text):JSON.parse(text);products=(Array.isArray(raw)?raw:raw.products||[]).map(normalizeProduct);save();log(`Imported ${products.length} products from ${f.name}`)};function parseCsv(text){const rows=text.trim().split(/\r?\n/).map(r=>r.split(',').map(x=>x.trim().replace(/^"|"$/g,'')));const headers=rows.shift();return rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]||''])))}
function templateListings(p){const base=`${p.name} from No Vanity 33. ${p.frontDesign}. ${p.backDesign?`Includes ${p.backDesign}.`:''} Available in ${p.colors.join(', ')} and sizes ${p.sizes.join(', ')}. Wear the Word. Live the Gospel. Spread the Truth.`;return Object.fromEntries(CHANNELS.map(c=>[c,{title:`${p.name} | Christian ${p.collection} Shirt`.slice(0,c==='etsy'?140:120),description:base,keywords:`Christian shirt, faith apparel, ${p.name}, No Vanity 33`,tags:['Christian shirt','faith apparel',p.collection],cta:'Shop at NoVanity33.com'}]))}
$('#generateSelectedBtn').onclick=()=>generateProducts(products.filter(p=>p.selected));async function generateProducts(list){if(!list.length)return log('No products selected');for(const p of list){log(`Generating ${p.name}…`);try{const r=await fetch('/api/generate-listing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product:p,channels:CHANNELS})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Generation failed');p.listings=d.listings;log(`Generated ${p.name}`)}catch(e){p.listings=templateListings(p);log(`Used safe template for ${p.name}`,{error:e.message})}}save()}
window.openEditor=id=>{activeProductId=id;activeChannel='etsy';$('#editorPanel').classList.remove('hidden');renderEditor();$('#editorPanel').scrollIntoView({behavior:'smooth'})};$('#closeEditor').onclick=()=>$('#editorPanel').classList.add('hidden');
function renderEditor(){const p=products.find(x=>x.id===activeProductId);if(!p)return;$('#editorProductName').textContent=p.name;$('#channelTabs').innerHTML=CHANNELS.map(c=>`<button class="tab ${c===activeChannel?'active':''}" onclick="switchChannel('${c}')">${c}</button>`).join('');const l=p.listings[activeChannel]||templateListings(p)[activeChannel];$('#editTitle').value=l.title||'';$('#editDescription').value=l.description||'';$('#editKeywords').value=l.keywords||'';$('#editTags').value=(l.tags||[]).join(', ');$('#editCta').value=l.cta||''}
window.switchChannel=c=>{saveEditor();activeChannel=c;renderEditor()};function saveEditor(){const p=products.find(x=>x.id===activeProductId);if(!p)return;p.listings[activeChannel]={title:$('#editTitle').value,description:$('#editDescription').value,keywords:$('#editKeywords').value,tags:$('#editTags').value.split(',').map(x=>x.trim()).filter(Boolean),cta:$('#editCta').value};save()}
$('#saveEdits').onclick=()=>{saveEditor();log(`Saved ${activeChannel} edits`)};$('#publishCurrent').onclick=()=>{saveEditor();publish([{product:products.find(x=>x.id===activeProductId),channels:[activeChannel]}])};$('#publishSelectedBtn').onclick=()=>publish(products.filter(p=>p.selected).map(product=>({product,channels:CHANNELS})));
async function publish(jobs){for(const job of jobs){for(const channel of job.channels){const p=job.product;if(!p.listings[channel]){log(`Skipped ${p.name} on ${channel}: generate first`);continue}try{const r=await fetch('/api/publish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({channel,product:p,listing:p.listings[channel]})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Publish failed');p.publishStatus[channel]=d.status||'draft';log(`${p.name} → ${channel}`,d)}catch(e){p.publishStatus[channel]='needs setup';log(`${channel} needs setup`,{product:p.name,error:e.message})}}}save()}
$('#downloadBtn').onclick=()=>{const blob=new Blob([JSON.stringify({products,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='catalogflow-products.json';a.click();URL.revokeObjectURL(a.href)};
function renderConnectors(c){const info={etsy:'OAuth + shop settings',tiktok:'Partner Center custom app',instagram:'Meta catalog/business app',pinterest:'Business catalog OAuth'};$('#connectors').innerHTML=CHANNELS.map(x=>`<div class="connector"><h3>${x[0].toUpperCase()+x.slice(1)}</h3><b class="${c[x]?'ready':'pending'}">${c[x]?'Connected':'Setup required'}</b><p>${info[x]}</p></div>`).join('')}init();